// <auto-generated />
using System;
using Distancify.Migrations.SqlMigration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Distancify.Migrations.Migrations.SqlMigration
{
    [DbContext(typeof(MigrationLogContext))]
    [Migration("20190719063501_MigrationLogTableMigration")]
    partial class MigrationLogTableMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Distancify.Migrations.SqlMigration.MigrationLog", b =>
                {
                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("RunnedAt");

                    b.HasKey("Type");

                    b.ToTable("__DistancifyMigrationLog");
                });
#pragma warning restore 612, 618
        }
    }
}
